apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-todo-app
  template:
    metadata:
      labels:
        app: django-todo-app
    spec:
      containers:
      - name: django-todo-container
        image: sandeep2862/django-todo:1
        ports:
        - containerPort: 8000
        env:
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: django-mysql-secret
              key: SECRET_KEY
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: django-mysql-secret
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: django-mysql-secret
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: django-mysql-secret
              key: DB_PASSWORD
        - name: DB_HOST
          value: "mysql-service"
        - name: DB_PORT
          value: "3306"
